import eimg1 from '/public/images/event/img-1.jpg'
import eimg2 from '/public/images/event/img-2.png'
import eimg3 from '/public/images/event/img-3.jpg'
import eimg4 from '/public/images/event/img-4.jpg'
import eimg5 from '/public/images/event/img-5.jpg'
import eimg6 from '/public/images/event/img-6.jpg'
import eimg7 from '/public/images/event/img-7.jpg'
import eimg8 from '/public/images/event/img-8.jpg'
import eimg9 from '/public/images/event/img-9.jpg'

const Events = [
    {
        id: '0',
        eImg: eimg4,
        date: "07 June, 2024",
        eTitle: 'Fundraising Cocktail Event',
        slug: 'fundraising-cocktail-event-2024',
        dec: 'Join us for an evening of inspiration and generosity at our Fundraising Cocktail Event in June. Together, we can make a difference by supporting our initiatives to improve lives and empower communities.',
        fullDec: {
            title1: "Join Us at Grace Life's Fundraising Cocktail Event: A Night of Impact and Inspiration",
            description1: "Our Fundraising Cocktail Event in June is more than just an event; it's an opportunity to come together as a community and make a meaningful difference. Join us for an evening of inspiration, entertainment, and generosity as we share our vision for a brighter future. Together, we can raise vital funds to support our initiatives and create positive change in the lives of those in need.",
            title2: "Making a Difference, Together",
            description2: "At Grace Life, we believe in the power of collective action to drive positive change. By attending our Fundraising Cocktail Event, you're not just enjoying delicious cocktails and great company – you're joining a movement to improve lives and empower communities. Every donation, big or small, makes a difference and helps us continue our vital work.",
            title3: "Supporting Our Mission",
            description3: "The funds raised at our Fundraising Cocktail Event will support a range of initiatives aimed at improving the lives of those in need. From providing essential resources to vulnerable communities to funding education and healthcare programs, your support will have a tangible and lasting impact. Together, we can create a brighter future for all.",
            title4: "Join Us for an Unforgettable Evening",
            description4: "Don't miss out on this opportunity to make a difference and be part of something special. Join us at our Fundraising Cocktail Event in June and help us continue our mission of making the world a better place for all. Together, we can achieve great things.",
        },
    },
    {
        id: '1',
        eImg: eimg5,
        date: "16 June, 2024",
        eTitle: 'Day of the African Child Commemorations',
        slug: 'african-child-day',
        dec: "Join us on June 16th as we commemorate the Day of the African Child. Together, we can advocate for the rights and well-being of children in Africa and work towards a brighter future for all.",
        fullDec: {
            title1: "Commemorating the Day of the African Child: Advocating for a Brighter Future",
            description1: "Every year on June 16th, the Day of the African Child provides an important opportunity to reflect on the rights and well-being of children across the continent. At Grace Life, we are committed to advocating for the rights of every child and ensuring they have the opportunity to thrive and reach their full potential.",
            title2: "Why June 16th Matters",
            description2: "June 16th holds special significance as it marks the anniversary of the 1976 Soweto uprising, where thousands of black South African students took to the streets to protest against the inferior quality of their education and to demand their right to be taught in their own language. Today, the Day of the African Child serves as a reminder of the ongoing challenges facing children in Africa and the need for continued advocacy and action.",
            title3: "Our Commitment to Children's Rights",
            description3: "At Grace Life, we believe that every child deserves to grow up in a safe, nurturing environment where their rights are respected and protected. Through our programs and initiatives, we work to ensure that children have access to education, healthcare, and protection from harm. Join us on June 16th as we come together to commemorate the Day of the African Child and advocate for a brighter future for all.",
            title4: "Get Involved",
            description4: "There are many ways to get involved in the Day of the African Child commemorations. Whether you participate in local events, raise awareness on social media, or support organizations working to improve children's lives, your actions can make a difference. Together, we can create a world where every child has the opportunity to thrive and succeed.",
        },
    },
    {
        id: '2',
        eImg: eimg6,
        date: "24 July, 2024",
        eTitle: 'Support for Gombekombe and Chigwida Labour Ward',
        slug: 'gombekombe-chigwida-labour-ward',
        dec: "Join us as we provide support to the Gombekombe and Chigwida Labour Ward in the Chiweshe area. Together, we can reduce infant mortality rates and improve maternal healthcare access for women in need.",
        fullDec: {
            title1: "Supporting Maternal Healthcare: A Community Initiative",
            description1: "Access to quality maternal healthcare is essential for ensuring the well-being of mothers and newborns. Unfortunately, many communities face barriers to accessing these vital services, including long distances to healthcare facilities and a lack of essential resources. At Grace Life, we are committed to addressing these challenges and improving maternal healthcare access for women in need.",
            title2: "Our Partnership with Gombekombe and Chigwida Labour Ward",
            description2: "We are proud to announce our partnership with the Gombekombe and Chigwida Labour Ward in the Chiweshe area. Through this collaboration, we will provide support and resources to improve maternal healthcare services and reduce infant mortality rates. Together, we can make a real difference in the lives of mothers and newborns in this community.",
            title3: "How You Can Help",
            description3: "You can support our efforts to improve maternal healthcare by donating essential resources, volunteering your time, or raising awareness about the importance of maternal and child health. Every contribution, no matter how small, helps us make a difference in the lives of women and children in need. Join us in supporting the Gombekombe and Chigwida Labour Ward and help us create a healthier, brighter future for all.",
            title4: "Together, We Can Make a Difference",
            description4: "By coming together as a community, we can make a real difference in the lives of mothers and newborns in the Chiweshe area. Join us in supporting the Gombekombe and Chigwida Labour Ward and help us improve maternal healthcare access and reduce infant mortality rates. Together, we can create a healthier, brighter future for all.",
        },
    },
    {
        id: '3',
        eImg: eimg7,
        date: "May 04, 2024",
        eTitle: 'Blanket Drive',
        slug: 'blanket-drive',
        dec: "Join us as we donate blankets to a selected children's home as part of our Care for A Soul program. Together, we can provide warmth and comfort to those in need and make a positive impact in our community.",
        fullDec: {
            title1: "Giving Back: Our Blanket Drive Initiative",
            description1: "Winter can be a challenging time for vulnerable communities, especially for children without adequate shelter or warmth. That's why we're launching our Blanket Drive initiative to provide comfort and support to those in need. Join us as we come together to make a positive impact in our community.",
            title2: "Our Commitment to Care for A Soul",
            description2: "At Grace Life, we believe in the importance of caring for the whole person – body, mind, and soul. Our Care for A Soul program aims to provide essential support and resources to those in need, including food, clothing, and shelter. By participating in our Blanket Drive initiative, you're helping us fulfill this mission and make a difference in the lives of others.",
            title3: "How You Can Help",
            description3: "You can support our Blanket Drive initiative by donating blankets, volunteering your time, or spreading the word about our cause. Every contribution, no matter how small, makes a difference and helps us provide warmth and comfort to those in need. Together, we can make a positive impact in our community and bring hope to those who need it most.",
            title4: "Join Us in Making a Difference",
            description4: "Join us as we come together to make a difference in the lives of children in need. Together, we can provide warmth and comfort to those facing the challenges of winter and bring hope to those who need it most. Together, we can make a positive impact in our community and create a brighter future for all.",
        },
    },
    {
        id: '4',
        eImg: eimg8,
        date: "Mid October, 2024",
        eTitle: 'Grace Life Foundation Marathon',
        slug: 'gracelife-marathon',
        dec: "Join us for the Grace Life Foundation Marathon in mid-October. Together, we can raise funds to support our Care for A Soul activities and make a positive impact in the lives of those in need.",
        fullDec: {
            title1: "Run with Purpose: The Grace Life Foundation Marathon",
            description1: "The Grace Life Foundation Marathon is more than just a race – it's an opportunity to make a difference in the lives of those in need. Join us as we come together to raise funds for our Care for A Soul activities and make a positive impact in our community.",
            title2: "Supporting Care for A Soul",
            description2: "At Grace Life, we're committed to caring for the whole person – body, mind, and soul. Our Care for A Soul activities provide essential support and resources to those facing the challenges of poverty, homelessness, and hunger. By participating in the Grace Life Foundation Marathon, you're helping us fulfill this mission and make a difference in the lives of others.",
            title3: "How You Can Participate",
            description3: "You can participate in the Grace Life Foundation Marathon by signing up to run, volunteering your time, or making a donation to support our cause. Whether you're an experienced runner or just looking to make a difference, there's a way for everyone to get involved. Together, we can make a positive impact in our community and bring hope to those who need it most.",
            title4: "Join Us in Making a Difference",
            description4: "Join us as we come together to run with purpose and make a difference in the lives of those in need. Together, we can raise funds to support our Care for A Soul activities and make a positive impact in our community. Together, we can create a brighter future for all.",
        },
    },
    {
        id: '5',
        eImg: eimg1,
        date: "15 Oct, 2023",
        eTitle: 'Cancer Run',
        slug: 'cancer-run',
        dec: 'Cancer awareness in Zimbabwe, as well as in other regions of the continent, falls short of the necessary prominence. The Cancer Run aims to generate funds for conducting cancer awareness initiatives in underserved communities throughout the country.',
        fullDec: {
            title1: "Join Us in the Fight Against Cancer: 2023 Cancer Run",
            description1: "Cancer is a global health challenge that affects millions of lives every year, and Zimbabwe is no exception. While progress has been made in understanding and treating this disease, cancer awareness and prevention efforts in Zimbabwe, as well as in many other parts of the continent, often lag behind the urgent need for widespread awareness and access to early detection and treatment. At Gracelife Foundation, we recognize that cancer awareness and support for individuals living with this disease are not as prominent as they should be. We believe that everyone, regardless of their background or location, deserves the opportunity to learn about cancer, access essential screenings, and receive the support they need. That's why we are proud to introduce the Cancer Run, an initiative aimed at raising funds for conducting cancer awareness campaigns and providing crucial support to marginalized communities all across Zimbabwe. The Cancer Run is more than just a fundraising event; it's a movement to make a lasting impact on the fight against cancer in our country.",
            title2: "Our Mission",
            description2: "The mission of the Cancer Run is clear and compelling: to raise funds that will enable us to run comprehensive cancer awareness campaigns in underserved and vulnerable communities throughout Zimbabwe. We believe that by increasing awareness about cancer prevention, early detection, and available resources, we can save lives and make a significant difference in the fight against this devastating disease.",
            title3: "How You Can Help",
            description3: "Join us in the fight against cancer by participating in the Cancer Run and making a donation to support our initiatives. Your contribution will go a long way in funding cancer awareness campaigns, providing screenings, and offering support to those affected by cancer. Whether you're a passionate advocate, a survivor, a caregiver, or simply someone who wants to make a difference, your involvement in the Cancer Run is invaluable. Together, we can raise the profile of cancer awareness in Zimbabwe, save lives, and work towards a future free from the fear of cancer.",
            title4: "Get Involved Today",
            description4: "To get involved, use this link to register -  ",
        },
    },
    {
        id: '6',
        eImg: eimg2,
        date: "23 Nov, 2023",
        eTitle: '16 Days Against Gender Based Violence',
        slug: 'gbv-awareness',
        dec: 'As Gracelife Foundation, we are dedicated to the fight against gender based violence. In that same spirit, we will be holding a 16-day online awareness blitz against GBV on our social platforms',
        fullDec: {
            title1: "Join the 16 Days Against Gender-Based Violence Campaign: Together We Stand",
            description1: 'At Gracelife Foundation, our commitment to creating a world free from violence, discrimination, and inequality is unwavering. In line with this mission, we are proud to announce our participation in the "16 Days Against Gender-Based Violence" campaign, a powerful global movement aimed at raising awareness and driving change.',
            title2: "The Urgency of the Issue",
            description2: "Gender-based violence (GBV) remains a pervasive and deeply entrenched problem that affects individuals and communities worldwide. It takes various forms, including physical, sexual, emotional, and economic violence, and it knows no boundaries of age, race, or social status. GBV not only inflicts immediate physical and psychological harm but also perpetuates cycles of fear, injustice, and disempowerment. This year, as we face unprecedented global challenges, the urgency of addressing GBV has become even more evident. The COVID-19 pandemic has exacerbated the prevalence of violence within homes, highlighting the need for collective action and awareness to combat this crisis.",
            title3: "The 16 Days Campaign",
            description3: 'The "16 Days Against Gender-Based Violence" campaign, observed annually from November 25th to December 10th, provides a vital platform for advocacy, education, and mobilization. These 16 days symbolize a call to action, spanning from the International Day for the Elimination of Violence Against Women on November 25th to International Human Rights Day on December 10th. Gracelife Foundation is proud to stand in solidarity with organizations, activists, and individuals worldwide during this crucial period. We believe that these 16 days serve as a catalyst for meaningful change, fostering understanding, empathy, and a shared commitment to ending GBV.',
            title5: "Our Online Awareness Blitz",
            description5: "In alignment with our mission and values, Gracelife Foundation will be hosting a 16-day online awareness blitz against GBV across all our social media platforms. During these 16 days, we will provide informative and thought-provoking content to educate, inspire, and empower.",
        },
    },
    {
        id: '7',
        eImg: eimg3,
        date: "1 Dec, 2023",
        eTitle: 'World AIDS Day',
        slug: 'international-aids-day',
        dec: "At Gracelife Foundation, we are committed to expressing our solidarity with individuals living with and impacted by HIV, while also honoring the memory of those we've lost to AIDS. The disparities that contribute to the AIDS epidemic are not insurmountable; we have the capacity to address them.",
        fullDec: {
            title1: "Uniting Against HIV/AIDS: Gracelife Foundation's World AIDS Day Commitment",
            description1: "Our dedication to creating positive change knows no bounds, and one day holds immense significance on our calendar: World AIDS Day. On this day, we come together to express our unwavering solidarity with individuals living with HIV, and we pay solemn tribute to the lives we've lost to AIDS. But more than that, we stand as a beacon of hope, reminding the world that the disparities perpetuating the AIDS epidemic are not insurmountable; together, we have the power to confront and overcome them.",
            title2: "A Day of Remembrance and Resolve",
            description2: "World AIDS Day, observed every year on December 1st, is a global call to action. It's a day when the world unites to raise awareness about HIV/AIDS, support those living with the virus, and remember the loved ones we've lost. But it's also a day of resolve, a reminder that the fight against HIV/AIDS is far from over, and that we must continue to work tirelessly to achieve an AIDS-free future.",
            title3: "Joining Hands for a Brighter Tomorrow",
            description3: 'On World AIDS Day, December 1st, we invite you to stand with us as we commemorate this significant day. Throughout the day, Gracelife Foundation will host an online educational session where we will delve deeper into the factors mentioned above. Our goal is to raise awareness, provide crucial information, and foster a sense of unity in the global fight against HIV/AIDS. Your support, whether through donations, volunteering, or advocacy, strengthens our resolve and enhances our impact. Together, we can accelerate progress towards an AIDS-free world, where every person is treated with dignity, and no one suffers the pain of discrimination or loss due to this preventable and treatable condition. As Gracelife Foundation, we believe in the power of unity and compassion. Join us in our mission to create a world where HIV/AIDS is no longer a source of fear or suffering, but a chapter in the history of human resilience and triumph. Together, we can make that vision a reality.',
            title5: "Our Online Awareness Blitz",
            description5: "In alignment with our mission and values, Gracelife Foundation will be hosting a full day online awareness blitz on AIDS Education across all our social media platforms. On this day we will provide informative and thought-provoking content to educate, inspire, and empower.",
        },
    },
]

export default Events;
